### ISSUE TITLE
关于S3DIS数据集处理代码

### ISSUE THREAD

**Issue by fengfeng19991001** [fpthink/3D-WSIS#1]
非常感谢你们的工作，请问大概什么时候会上传S3DIS数据集训练和测试的代码？

**Comment by fpthink** [comment]
> 非常感谢你们的工作，请问大概什么时候会上传S3DIS数据集训练和测试的代码？

The code of S3DIS will be released on Nov.15.

**Comment by fengfeng19991001** [comment]
Thank you very much!

**Comment by ttttlh** [comment]
> 

Hi, we have pushed the code for the S3DIS dataset.

**Comment by ttttlh** [comment]
> 非常感谢你们的工作，请问大概什么时候会上传S3DIS数据集训练和测试的代码？

Hi, we have pushed the code for the S3DIS dataset.

**Comment by fengfeng19991001** [comment]
Thanks!
